"""llama.cpp router mode: models.ini presets plus a manifest other tools can read.

Preset format, as served back by a live router's /models endpoint:
    [<model id>]
    <llama-server long flag without "--"> = <value>      (switches use "= 1")

A running router re-reads the preset file on GET /models?reload=1. Models whose section
is unchanged stay loaded; a loaded model whose section changed is unloaded.
"""
from __future__ import annotations

import json
import os
import re
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from . import flags as flagmod
from . import gguf, profiles, scanner
from .store import config_dir

# The router owns these (it assigns child host/port/alias and strips API keys).
ROUTER_RESERVED_KEYS = frozenset({"host", "port", "alias", "api_key", "metrics", "no_webui"})
MAX_OUTPUT_TOKENS = 32768

_capability_cache: dict[tuple[str, int, int], dict] = {}


def ini_path() -> Path:
    return config_dir() / "models.ini"


def manifest_path() -> Path:
    return config_dir() / "local-llama.json"


def model_id(repo: scanner.ModelRepo, quant: scanner.GgufFile, copy: int = 1) -> str:
    """The id a model is published and served under. `copy` > 1 tells apart library entries
    that would otherwise share an id (the same repo and quant found in two places)."""
    owner = repo.owner or "local"
    # llama-server rewrites a preset's tag to its last "-"/"." separated word, upper-cased
    # ("APEX-I-Quality" is served as "QUALITY"), so a file name without a quant token has to
    # become a tag it leaves alone, or the id published here differs from the one it serves.
    # For the same reason the copy number goes on the name, never on the tag.
    tag = quant.label or re.sub(r"[^A-Za-z0-9]+", "_", quant.path.stem).strip("_").upper()
    name = repo.name if copy <= 1 else f"{repo.name}-{copy}"
    return f"{owner}/{name}:{tag}"


def ignored_extra(extra: str) -> list[str]:
    """Extra-argument tokens a preset cannot carry: presets only have --long keys, so a short
    flag such as -ngl (and its value) would be dropped without a word."""
    tokens = flagmod.split_extra(extra)
    return [t for t in tokens if re.fullmatch(r"-[A-Za-z][\w-]*", t)]


def _pairs(tokens: list[str]) -> list[tuple[str, str]]:
    """argv tokens -> preset key/value pairs. Only --long flags map onto preset keys."""
    pairs: list[tuple[str, str]] = []
    i = 0
    while i < len(tokens):
        token = tokens[i]
        if not token.startswith("--"):
            i += 1
            continue
        key = token[2:]
        if i + 1 < len(tokens) and not tokens[i + 1].startswith("--"):
            pairs.append((key, tokens[i + 1].strip('"')))
            i += 2
        else:
            pairs.append((key, "1"))
            i += 1
    return pairs


def _capabilities(path: Path) -> dict:
    try:
        st = path.stat()
    except OSError:
        return {}
    key = (str(path).lower(), st.st_size, int(st.st_mtime))
    if key not in _capability_cache:
        _capability_cache[key] = gguf.read_capabilities(path)
    return _capability_cache[key]


def _context_for(values: dict, quant: scanner.GgufFile) -> int:
    ctx = int(values.get("ctx_size") or 0)
    if ctx > 0:
        return ctx
    return int(gguf.summarize(gguf.read_metadata(quant.path)).get("n_ctx_train") or 0)


def build(store, repos: list[scanner.ModelRepo]) -> tuple[str, dict[str, Any]]:
    """Render models.ini text and the manifest for every quant in the library."""
    sections: list[str] = ["; Generated by LLM Switchboard - edits here are overwritten on rescan.", ""]
    models: list[dict[str, Any]] = []
    seen: set[str] = set()

    for repo in repos:
        for quant in repo.quants:
            copy = 1
            mid = model_id(repo, quant)
            while mid in seen:
                copy += 1
                mid = model_id(repo, quant, copy)
            seen.add(mid)

            values, extra = profiles.resolve(store, repo, quant)
            lines = [f"[{mid}]", f"model = {quant.path}"]
            for spec in flagmod.SPECS:
                if spec.key in ROUTER_RESERVED_KEYS or spec.key not in values:
                    continue
                for key, value in _pairs(spec.emit(values[spec.key])):
                    lines.append(f"{key} = {value}")
            for key, value in _pairs(flagmod.split_extra(extra)):
                lines.append(f"{key} = {value}")
            sections.extend(lines)
            sections.append("")

            caps = _capabilities(quant.path)
            input_modalities = ["text"]
            mmproj = values.get("mmproj")
            if mmproj:
                projector = _capabilities(Path(mmproj))
                if projector.get("vision", True):
                    input_modalities.append("image")
                if projector.get("audio"):
                    input_modalities.append("audio")

            context = _context_for(values, quant)
            models.append({
                "id": mid,
                "name": f"{repo.name} ({quant.label or 'GGUF'})",
                "owner": repo.owner,
                "context": context,
                "output": min(MAX_OUTPUT_TOKENS, context // 2) if context else MAX_OUTPUT_TOKENS,
                "modalities": input_modalities,
                "reasoning": bool(caps.get("reasoning")),
                "tool_call": bool(caps.get("tools", True)),
            })

    return "\n".join(sections), {"version": 1, "models": models}


# The router and NInfer both own parts of the manifest and are published from worker
# threads, which can now overlap: both engines run at once. Every read-modify-write of the
# manifest goes through this lock, or one publish silently drops the other's key.
MANIFEST_LOCK = threading.RLock()


def write_if_changed(path: Path, text: str) -> bool:
    try:
        if path.read_text(encoding="utf-8") == text:
            return False
    except OSError:
        pass
    # A name of its own per writer: two publishes can overlap on worker threads.
    tmp = path.with_suffix(f"{path.suffix}.{threading.get_ident()}.tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)
    return True


def _sections(text: str) -> dict[str, str]:
    sections: dict[str, list[str]] = {}
    current = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            current = stripped[1:-1]
            sections[current] = []
        elif current is not None and stripped and not stripped.startswith(";"):
            sections[current].append(stripped)
    return {name: "\n".join(lines) for name, lines in sections.items()}


def read_sections() -> dict[str, str]:
    try:
        return _sections(ini_path().read_text(encoding="utf-8"))
    except OSError:
        return {}


def diff(applied: dict[str, str], current: dict[str, str]) -> list[str]:
    return sorted(name for name in applied.keys() | current.keys() if applied.get(name) != current.get(name))


def publish(store, repos: list[scanner.ModelRepo], values: dict[str, Any]) -> list[str]:
    """Write models.ini and the manifest. Returns ids whose preset was added, removed or changed."""
    ini_text, manifest = build(store, repos)
    manifest["baseURL"] = f"{_base_url(values)}/v1"
    manifest["apiKey"] = str(values.get("api_key") or "")
    manifest["iniPath"] = str(ini_path())

    changed = diff(read_sections(), _sections(ini_text))
    write_if_changed(ini_path(), ini_text)
    with MANIFEST_LOCK:
        previous = {}
        try:
            previous = json.loads(manifest_path().read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            pass
        previous.pop("generated", None)
        # The running NInfer server is advertised in the same file; a library rescan must not drop it.
        if "ninfer" in previous:
            manifest["ninfer"] = previous["ninfer"]
        if previous != manifest:
            manifest["generated"] = time.strftime("%Y-%m-%dT%H:%M:%S")
            write_if_changed(manifest_path(), json.dumps(manifest, indent=2))
    return changed


def argv(binary: str, values: dict[str, Any]) -> list[str]:
    out = [str(binary), "--models-preset", str(ini_path()), "--models-max", "1",
           "--host", str(values.get("host") or "127.0.0.1"),
           "--port", str(int(values.get("port") or 8080))]
    if values.get("api_key"):
        out += ["--api-key", str(values["api_key"])]
    return out


def _base_url(values: dict[str, Any]) -> str:
    host = str(values.get("host") or "127.0.0.1")
    host = "127.0.0.1" if host in ("0.0.0.0", "") else host
    return f"http://{host}:{int(values.get('port') or 8080)}"


def _get(values: dict[str, Any], path: str, timeout: float) -> dict:
    request = urllib.request.Request(f"{_base_url(values)}{path}")
    if values.get("api_key"):
        request.add_header("Authorization", f"Bearer {values['api_key']}")
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return json.loads(response.read().decode("utf-8"))


def loaded_models(values: dict[str, Any], timeout: float = 3.0) -> list[str] | None:
    """Ids the router currently has loaded or loading; None when it is unreachable."""
    try:
        data = _get(values, "/models", timeout)
    except (urllib.error.URLError, OSError, ValueError):
        return None
    return [m.get("id", "") for m in data.get("data", [])
            if (m.get("status") or {}).get("value") in ("loaded", "loading")]


def reload(values: dict[str, Any], timeout: float = 20.0) -> bool:
    """Make a running router re-read models.ini without restarting it."""
    try:
        _get(values, "/models?reload=1", timeout)
        return True
    except (urllib.error.URLError, OSError, ValueError):
        return False
